language: ruby
cache:
  apt: true
  bundler: true
  directories:
    - vendor/bundle
addons:
  postgresql: "9.3"
  apt:
    packages:
      - sphinxsearch
rvm:
  - 2.1
  - 2.0
  - 1.9
sudo: false
env:
  - REDMINE_VERSION=2.4.7 VERBOSE=no DB=mysql
  - REDMINE_VERSION=2.5.3 VERBOSE=no DB=mysql
  - REDMINE_VERSION=2.6.0 VERBOSE=no DB=mysql
  - REDMINE_VERSION=master VERBOSE=no DB=mysql
  - REDMINE_VERSION=2.4.7 VERBOSE=no DB=postgres
  - REDMINE_VERSION=2.5.3 VERBOSE=no DB=postgres
  - REDMINE_VERSION=2.6.0 VERBOSE=no DB=postgres
  - REDMINE_VERSION=master VERBOSE=no DB=postgres
  - REDMINE_VERSION=2.4.7 VERBOSE=no DB=sqlite
  - REDMINE_VERSION=2.5.3 VERBOSE=no DB=sqlite
  - REDMINE_VERSION=2.6.0 VERBOSE=no DB=sqlite
  - REDMINE_VERSION=master VERBOSE=no DB=sqlite
script:
  - bash ./.travis-redmine-helper.sh
before_script:
  - mysql -e 'create database didyoumean_test;'
  - psql -c 'create database didyoumean_test;' -U postgres
